{{- if .Values.migrations.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "api-server.fullname" . }}-migrations"
  labels:
    {{- include "api-server.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: {{ .Values.migrations.job.backoffLimit }}
  template:
    spec:
      containers:
        - name: migrations
          image: "{{ .Values.migrations.image.repository }}:{{ .Values.migrations.image.tag }}"
          imagePullPolicy: {{ .Values.migrations.image.pullPolicy }}
          command: ["sh", "-c", "python manage.py migrate"]
      restartPolicy: OnFailure
{{- end }}
